# Generated by Django 3.2.7 on 2021-09-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlistings_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='imageUrl',
            field=models.CharField(blank=True, default="{% static 'auctions/media/img.jpg' %}", max_length=500, null=True),
        ),
    ]
