# Generated by Django 3.2.7 on 2021-09-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlistings_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='imageUrl',
            field=models.CharField(blank=True, default='https://cdn-icons-png.flaticon.com/512/3125/3125669.png', max_length=500, null=True),
        ),
    ]
