# Generated by Django 3.2.7 on 2021-09-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlistings_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='starting_bid',
            field=models.FloatField(),
        ),
    ]
