# Generated by Django 3.2.7 on 2021-09-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlistings_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='current_bid',
            field=models.FloatField(),
        ),
    ]
