# Generated by Django 3.2.7 on 2021-09-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bids_current_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='current_bid',
            new_name='current_price',
        ),
    ]
