# Generated by Django 3.2.7 on 2021-09-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_current_bid_bids_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
