# Generated by Django 3.2.7 on 2021-09-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bids_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
